### ISSUE TITLE
Error with recursive Composer dependencies

### ISSUE THREAD

**Issue by filips123** [theseer/Autoload#83]
## Description

There is nesting error with some Composer dependencies. This happens when some dependency have a lot of dependencies which sometimes require back original dependency.

In my case, package `cakephp/core` requires `cakephp/utility` which requires `cakephp/core` and so on. This is because I have `robmorgan/phinx` and it depends on `cakephp/core`.

![dependencies](https://user-images.githubusercontent.com/16626308/52524627-3c069f80-2c9f-11e9-92bf-c5b71304bd61.png)

## Log

```
phpab 1.25.2 - Copyright (C) 2009 - 2019 by Arne Blankerts and Contributors

PHP Fatal error:  Uncaught Error: Maximum function nesting level of '8192' reached, aborting! in phar:///usr/local/bin/phpab/phpab/ComposerIterator.php:76
Stack trace:
#0 phar:///usr/local/bin/phpab/phpab/ComposerIterator.php(76): file_exists('/projects/Sunsh...')
#1 phar:///usr/local/bin/phpab/phpab/ComposerIterator.php(56): TheSeer\Autoload\ComposerIterator->findComposerJson('/projects/Sunsh...')
#2 phar:///usr/local/bin/phpab/phpab/ComposerIterator.php(64): TheSeer\Autoload\ComposerIterator->processRequire('/projects/Sunsh...', 'cakephp/utility')
#3 phar:///usr/local/bin/phpab/phpab/ComposerIterator.php(64): TheSeer\Autoload\ComposerIterator->processRequire('/projects/Sunsh...', 'cakephp/utility')
#4 phar:///usr/local/bin/phpab/phpab/ComposerIterator.php(64): TheSeer\Autoload\ComposerIterator->processRequire('/projects/Sunsh...', 'cakephp/core')
#5 phar:///usr/local/bin/phpab/phpab/ComposerIterator.php(64): TheSeer\Autoload\ComposerIterator->processRequire('/projects/Sunsh...', 'cakephp/utility')
#6 phar:///usr/local/bin/ph in phar:///usr/local/bin/phpab/phpab/ComposerIterator.php on line 76
```

## Required packages

(part of composer.json)

```
{
    "require": {
        "php": ">= 5.5.9",
        "slim/slim": "^3.0",
        "league/plates": "^3.0",
        "robmorgan/phinx": "^0.9|^0.10",
        "illuminate/database": "^5.0",
        "filp/whoops": "^2.0",
        "monolog/monolog": "^1.0",
        "phpmailer/phpmailer": "^6.0",
        "filips123/monolog-phpmailer": "^1.0",
        "filips123/eventy": "^0.6",
        "nadar/php-composer-reader": "^1.0", 
        "willdurand/negotiation": "^3.0@alpha"
    }
}
```

**Comment by theseer** [comment]
Nice catch. Stupid mistake ;)
